"""Add processing status fields to Project

Revision ID: b80bf8a79fa3
Revises: 47789f80b9eb
Create Date: 2025-12-12 08:58:59.392725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80bf8a79fa3'
down_revision = '47789f80b9eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'annotation_reviews', 'annotations', ['annotation_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'tasks', ['related_task_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'annotations', ['related_annotation_id'], ['id'])
    op.add_column('projects', sa.Column('is_processing', sa.Boolean(), nullable=False, server_default=sa.text("false")))
    op.add_column('projects', sa.Column('last_processed_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('processing_status', sa.String(length=50), nullable=True))
    op.add_column('projects', sa.Column('processing_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'processing_error')
    op.drop_column('projects', 'processing_status')
    op.drop_column('projects', 'last_processed_at')
    op.drop_column('projects', 'is_processing')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'annotation_reviews', type_='foreignkey')
    # ### end Alembic commands ###
